build:
  stage: build
  image: docker:19.03.1
  services:
    - docker:dind
    - name: gitlab/gitlab-ce:12.7.0-ce.0
      alias: gitlab
  variables:
    FF_NETWORK_PER_BUILD: "true"          # activate container2container networking
    DOCKER_OPTS: "--network=host -i"      # inter-container networking only works with `host`
    GITLAB_HTTPS: "false"                 # ensure that plain http will work
    GITLAB_ROOT_PASSWORD: "password"      # password is hardcoded in the tests
    URL: "http://gitlab/api/v4/projects"  # URL used for health check of the gitlab container
  before_script:
    - bin/reverse-proxy http://gitlab:80  # spin up a reverse proxy because the java tests are hardcoded to localhost
    - sleep 60                            # Give Gitlab some time - otherwise the curl connection will fail
    - echo "Waiting for Gitlab to boot"
    - until [ "$(bin/curl --silent --output /dev/null -w ''%{http_code}'' "$URL")" = "200" ]; do
        echo "Pinging http://gitlab/api/v4/projects $(bin/curl --silent --output /dev/null -w ''%{http_code}'' "$URL")";
        sleep 5;
        done;
    - echo "Pinging http://gitlab/api/v4/projects:$(bin/curl --silent --output /dev/null -w ''%{http_code}'' "$URL")"
    - echo "Pinging http://localhost/api/v4/projects:$(bin/curl --silent --output /dev/null -w ''%{http_code}'' "$URL")"
  script: bin/gradle jvmTest

#docker build --tag gitlab-sdk:snapshot -f Dockerfile.test . && docker run --rm gitlab-sdk:snapshot
